-- Create dogs table
CREATE TABLE IF NOT EXISTS public.dogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    breed TEXT NOT NULL,
    description TEXT,
    image TEXT,
    age INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create parents table for storing parent relationships
CREATE TABLE IF NOT EXISTS public.dog_parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dog_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    father_id BIGINT REFERENCES public.dogs(id),
    mother_id BIGINT REFERENCES public.dogs(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(dog_id)
);

-- Create siblings table for storing sibling relationships
CREATE TABLE IF NOT EXISTS public.dog_siblings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dog_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    sibling_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(dog_id, sibling_id)
);

-- Create offspring table for storing offspring relationships
CREATE TABLE IF NOT EXISTS public.dog_offspring (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dog_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    offspring_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(dog_id, offspring_id)
);

-- Create achievements table
CREATE TABLE IF NOT EXISTS public.dog_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dog_id BIGINT NOT NULL REFERENCES public.dogs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_dogs_breed ON public.dogs(breed);
CREATE INDEX IF NOT EXISTS idx_dog_parents_dog_id ON public.dog_parents(dog_id);
CREATE INDEX IF NOT EXISTS idx_dog_parents_father_id ON public.dog_parents(father_id);
CREATE INDEX IF NOT EXISTS idx_dog_parents_mother_id ON public.dog_parents(mother_id);
CREATE INDEX IF NOT EXISTS idx_dog_siblings_dog_id ON public.dog_siblings(dog_id);
CREATE INDEX IF NOT EXISTS idx_dog_siblings_sibling_id ON public.dog_siblings(sibling_id);
CREATE INDEX IF NOT EXISTS idx_dog_offspring_dog_id ON public.dog_offspring(dog_id);
CREATE INDEX IF NOT EXISTS idx_dog_offspring_offspring_id ON public.dog_offspring(offspring_id);
CREATE INDEX IF NOT EXISTS idx_dog_achievements_dog_id ON public.dog_achievements(dog_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers to automatically update updated_at
CREATE TRIGGER update_dogs_updated_at
    BEFORE UPDATE ON public.dogs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dog_parents_updated_at
    BEFORE UPDATE ON public.dog_parents
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dog_achievements_updated_at
    BEFORE UPDATE ON public.dog_achievements
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE public.dogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dog_parents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dog_siblings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dog_offspring ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dog_achievements ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Allow public read access to dogs"
    ON public.dogs FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access to dog_parents"
    ON public.dog_parents FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access to dog_siblings"
    ON public.dog_siblings FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access to dog_offspring"
    ON public.dog_offspring FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access to dog_achievements"
    ON public.dog_achievements FOR SELECT
    USING (true); 