-- Create a function to convert comma-separated tags to array
CREATE OR REPLACE FUNCTION convert_tags_to_array(tags_text TEXT)
RETURNS TEXT[] AS $$
BEGIN
    RETURN string_to_array(tags_text, ',');
END;
$$ LANGUAGE plpgsql;

-- Insert blog posts
INSERT INTO blog_posts (title, content, image_url, author, tags) VALUES
('Welcome to Speedex Kennels', 'Welcome to our blog! Here we''ll share updates about our dogs, training progress, and upcoming events. Stay tuned for more exciting content!', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('welcome,introduction')),
('Training Tips for German Shepherds', 'German Shepherds are intelligent and eager to learn. Here are some essential tips for effective training: 1. Start early with basic commands 2. Use positive reinforcement 3. Be consistent with commands 4. Practice short sessions frequently 5. Socialize your puppy early. Remember, every dog learns at their own pace!', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('training,german shepherd,tips')),
('Understanding German Shepherd Temperament', 'German Shepherds are known for their intelligence, loyalty, and protective nature. In this post, we explore their temperament traits, how to work with their natural instincts, and what makes them such excellent working dogs.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('german shepherd,temperament,breed characteristics')),
('Daily Life at Speedex Kennels', 'A day in the life at our kennel includes early morning walks, training sessions, playtime, and grooming. We maintain strict schedules to ensure our dogs get the best care and training possible.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('daily life,kennel,behind the scenes')),
('Nutrition Guide for Working Dogs', 'Proper nutrition is crucial for working German Shepherds. We share our recommended diet plans, supplements, and feeding schedules to keep your dog in peak condition.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('nutrition,health,feeding')),
('Socialization Techniques for Puppies', 'Early socialization is key to raising a well-adjusted German Shepherd. Learn about our proven techniques for introducing puppies to new experiences, people, and other dogs.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('socialization,puppy training,development')),
('Competition Preparation', 'Preparing for dog shows and competitions requires dedication and proper training. We share our tips for getting your German Shepherd ready for the ring.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('competition,shows,preparation')),
('Grooming Tips for German Shepherds', 'Regular grooming is essential for maintaining your German Shepherd''s coat and overall health. Learn about our recommended grooming routine and products.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('grooming,maintenance,health')),
('Understanding Working Line vs Show Line', 'Learn about the differences between working line and show line German Shepherds, and how to choose the right one for your needs.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('breed lines,selection,information')),
('Training Equipment Guide', 'A comprehensive guide to essential training equipment for German Shepherds, from basic leashes to advanced training tools.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('equipment,training tools,guide')),
('Health and Wellness Tips', 'Keep your German Shepherd healthy with our comprehensive guide to preventive care, exercise routines, and regular health checks.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('health,wellness,preventive care')),
('Advanced Training Techniques', 'Take your German Shepherd''s training to the next level with these advanced techniques and exercises.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('advanced training,techniques,exercises')),
('Building a Strong Bond', 'Learn how to develop and strengthen the bond between you and your German Shepherd through trust, respect, and consistent training.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('bonding,relationship,trust')),
('Common Training Mistakes', 'Avoid these common training mistakes that can hinder your German Shepherd''s progress and development.', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('mistakes,training tips,avoidance')),
('Success Stories', 'Read about some of our most successful training cases and how we helped transform challenging situations into success stories.', 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 'Admin', convert_tags_to_array('success stories,case studies,transformations')); 